import type { EmergencyNumber } from "@/types";

/**
 * Emergency helplines, editable without touching UI components.
 *
 * - `region: "IN"` entries apply nationwide; add ISO 3166-2 entries (e.g. "IN-OR") for state
 *   numbers. A state entry with the same `id` as a national one overrides it for that state.
 * - Administrators can also add/override entries at runtime from /admin/helplines (stored in the
 *   `emergency_numbers` table); database rows take precedence over this file.
 * - Numbers were compiled from public Government of India sources. Availability differs between
 *   states and changes over time: RE-VERIFY EVERY NUMBER FOR YOUR PILOT REGION BEFORE LAUNCH.
 *   112 is listed first everywhere because it is the national single emergency number (ERSS).
 */
export const EMERGENCY_NUMBERS_REVIEWED = "2026-10-03";

type ConfigNumber = Omit<EmergencyNumber, "updatedAt" | "active"> & { source: string };

export const EMERGENCY_NUMBERS: ConfigNumber[] = [
  {
    id: "erss-112",
    country: "IN",
    region: "IN",
    name: "Emergency Response (ERSS)",
    purpose: "Single emergency number for police, fire and ambulance. Use this first if unsure.",
    number: "112",
    category: "emergency",
    availabilityNotes:
      "Available across India 24×7. Usually works even without balance; on most phones it also works without a SIM.",
    priority: 1,
    source: "https://112.gov.in",
  },
  {
    id: "police-100",
    country: "IN",
    region: "IN",
    name: "Police",
    purpose: "Police control room.",
    number: "100",
    category: "police",
    availabilityNotes: "In many states 100 now forwards to 112. If it does not connect, dial 112.",
    priority: 10,
    source: "https://112.gov.in",
  },
  {
    id: "ambulance-108",
    country: "IN",
    region: "IN",
    name: "Ambulance",
    purpose: "Emergency medical ambulance service.",
    number: "108",
    category: "ambulance",
    availabilityNotes: "Operated by state governments; coverage varies by state. If it does not connect, dial 112.",
    priority: 20,
    source: "https://nhm.gov.in",
  },
  {
    id: "ambulance-102",
    country: "IN",
    region: "IN",
    name: "Ambulance (mother & child)",
    purpose: "Ambulance for pregnant women and sick infants in many states.",
    number: "102",
    category: "ambulance",
    availabilityNotes: "Available in many states under the National Health Mission; scope differs by state.",
    priority: 25,
    source: "https://nhm.gov.in",
  },
  {
    id: "women-181",
    country: "IN",
    region: "IN",
    name: "Women Helpline",
    purpose: "24×7 support, referral and emergency response for women facing violence (One Stop Centre network).",
    number: "181",
    category: "women",
    availabilityNotes: "Operational in most states and UTs; integrated with 112 in several states.",
    priority: 30,
    source: "https://wcd.gov.in",
  },
  {
    id: "women-1091",
    country: "IN",
    region: "IN",
    name: "Women in Distress (Police)",
    purpose: "Police helpline for women in distress.",
    number: "1091",
    category: "women",
    availabilityNotes: "Operated by state/city police; not available everywhere. If it does not connect, dial 112.",
    priority: 35,
    source: "https://112.gov.in",
  },
  {
    id: "ncw-7827170170",
    country: "IN",
    region: "IN",
    name: "National Commission for Women",
    purpose: "Helpline for women affected by violence, including domestic violence.",
    number: "7827170170",
    category: "women",
    availabilityNotes: "Run by the National Commission for Women. Not an emergency response line: for immediate danger dial 112.",
    priority: 40,
    source: "https://ncw.nic.in",
  },
  {
    id: "child-1098",
    country: "IN",
    region: "IN",
    name: "Child Helpline",
    purpose: "Help for children in need of care and protection.",
    number: "1098",
    category: "child",
    availabilityNotes: "24×7 nationwide; integrated with the 112 emergency system.",
    priority: 45,
    source: "https://wcd.gov.in",
  },
  {
    id: "fire-101",
    country: "IN",
    region: "IN",
    name: "Fire",
    purpose: "Fire and rescue services.",
    number: "101",
    category: "fire",
    availabilityNotes: "State fire services; also reachable through 112.",
    priority: 50,
    source: "https://112.gov.in",
  },
  {
    id: "cyber-1930",
    country: "IN",
    region: "IN",
    name: "Cyber Crime Helpline",
    purpose: "Report online fraud, harassment and cyber crime. Also report at cybercrime.gov.in.",
    number: "1930",
    category: "cyber",
    availabilityNotes: "Nationwide. For online stalking or threats, also keep screenshots as evidence.",
    priority: 60,
    source: "https://cybercrime.gov.in",
  },
  {
    id: "tele-manas-14416",
    country: "IN",
    region: "IN",
    name: "Tele MANAS (mental health)",
    purpose: "Free 24×7 mental health support and counselling.",
    number: "14416",
    category: "other",
    availabilityNotes: "Nationwide, multiple languages. Also reachable at 1-800-891-4416.",
    priority: 70,
    source: "https://telemanas.mohfw.gov.in",
  },
  {
    id: "disaster-1078",
    country: "IN",
    region: "IN",
    name: "Disaster Management",
    purpose: "National Disaster Management Authority helpline.",
    number: "1078",
    category: "disaster",
    availabilityNotes: "For floods, cyclones and other disasters. For personal emergencies dial 112.",
    priority: 80,
    source: "https://ndma.gov.in",
  },
];

/** Regions offered in Settings. ISO 3166-2:IN codes. */
export const SUPPORTED_REGIONS: Array<{ code: string; name: string }> = [
  { code: "IN", name: "All India" },
  { code: "IN-AN", name: "Andaman and Nicobar Islands" },
  { code: "IN-AP", name: "Andhra Pradesh" },
  { code: "IN-AR", name: "Arunachal Pradesh" },
  { code: "IN-AS", name: "Assam" },
  { code: "IN-BR", name: "Bihar" },
  { code: "IN-CH", name: "Chandigarh" },
  { code: "IN-CT", name: "Chhattisgarh" },
  { code: "IN-DH", name: "Dadra and Nagar Haveli and Daman and Diu" },
  { code: "IN-DL", name: "Delhi" },
  { code: "IN-GA", name: "Goa" },
  { code: "IN-GJ", name: "Gujarat" },
  { code: "IN-HR", name: "Haryana" },
  { code: "IN-HP", name: "Himachal Pradesh" },
  { code: "IN-JK", name: "Jammu and Kashmir" },
  { code: "IN-JH", name: "Jharkhand" },
  { code: "IN-KA", name: "Karnataka" },
  { code: "IN-KL", name: "Kerala" },
  { code: "IN-LA", name: "Ladakh" },
  { code: "IN-LD", name: "Lakshadweep" },
  { code: "IN-MP", name: "Madhya Pradesh" },
  { code: "IN-MH", name: "Maharashtra" },
  { code: "IN-MN", name: "Manipur" },
  { code: "IN-ML", name: "Meghalaya" },
  { code: "IN-MZ", name: "Mizoram" },
  { code: "IN-NL", name: "Nagaland" },
  { code: "IN-OR", name: "Odisha" },
  { code: "IN-PY", name: "Puducherry" },
  { code: "IN-PB", name: "Punjab" },
  { code: "IN-RJ", name: "Rajasthan" },
  { code: "IN-SK", name: "Sikkim" },
  { code: "IN-TN", name: "Tamil Nadu" },
  { code: "IN-TG", name: "Telangana" },
  { code: "IN-TR", name: "Tripura" },
  { code: "IN-UP", name: "Uttar Pradesh" },
  { code: "IN-UT", name: "Uttarakhand" },
  { code: "IN-WB", name: "West Bengal" },
];

/** Numbers used by the emergency screen's "Call police" / "Call ambulance" buttons. */
export const PRIMARY_DIAL = {
  emergency: "erss-112",
  police: "police-100",
  ambulance: "ambulance-108",
} as const;
